Improve backend validation + add update question endpoint
CS3219-AY2324S1/ay2324s1-course-assessment-g49 pull request #14
Opened 2023-10-02 06:03 UTC by moreTriangles

2023-10-08 13:38 UTC, rachelkeh requested changes
Looks good!👍 Just some small questions that I'm curious about

2023-10-08 13:38 UTC, rachelkeh commented on openapi.yml
> +    UpdateQuestionRequest:
do you by any chance mean to use this anywhere else in the docs, specifically the patch endpoint docs above? bc i don't see it used anywhere, or maybe this is only for documentation purpose?

2023-10-08 13:38 UTC, rachelkeh commented on peerprep-backend/src/main/java/com/peerprep/peerprepbackend/controller/RestExceptionHandler.java
> +    @ExceptionHandler(HttpMessageNotReadableException.class)
hmm idk why when i send an empty update request like in the pic, it sends an ok response instead of the bad request response in the exception handler,
<img width="958" alt="image" src="https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g49/assets/70307497/2773b038-872f-4d32-99c3-6b7ab0f811a3">
but the console does show that the program goes into the exception handler
<img width="959" alt="image" src="https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g49/assets/70307497/3fce1358-8de1-440d-b1f4-d4955fd37c9e">

or is this the expected response?

2023-10-08 13:38 UTC, rachelkeh commented on peerprep-backend/src/main/java/com/peerprep/peerprepbackend/dto/request/UpdateQuestionRequest.java
> +    String description;
when i update the title as a string with only whitespaces, it goes through

<img width="956" alt="image" src="https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g49/assets/70307497/83fc0f1d-06d1-499c-9d51-57053c0430e8">
<img width="1091" alt="image" src="https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g49/assets/70307497/a792e2cc-d2d1-4496-a6ba-f6f74dc4c1c2">

not really an error, but do you think we should enforce this or nah? also, i forgot to validate my update user request rip....

2023-10-10 08:47 UTC, moreTriangles commented on openapi.yml
> +    UpdateQuestionRequest:
forgot to add the request body, thanks for catching

2023-10-10 08:50 UTC, adamozh commented on peerprep-backend/src/main/java/com/peerprep/peerprepbackend/controller/RestExceptionHandler.java
> +    @ExceptionHandler(HttpMessageNotReadableException.class)
Hmm I couldn't reproduce this, could you check again?

2023-10-10 11:09 UTC, moreTriangles commented on peerprep-backend/src/main/java/com/peerprep/peerprepbackend/dto/request/UpdateQuestionRequest.java
> +    String description;
Validated in frontend

2023-10-10 11:10 UTC, rachelkeh approved these changes

2023-10-10 11:10 UTC, merged